# Use the official Node.js image as base
FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the rest of the application source code to the container
COPY . .

# Command to run the application
CMD ["node", "app.js"]
